version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "kesterDL"
    assignees:
      - "kesterDL"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/Pi_Zero"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "kesterDL"
    assignees:
      - "kesterDL"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
